2020-06-30 16:56:27,099 - werkzeug:113 - INFO -  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2020-06-30 19:26:15,659 - werkzeug:113 - INFO -  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2020-06-30 19:37:14,144 - werkzeug:113 - INFO -  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2020-06-30 19:37:24,445 - flask:1892 - ERROR - Exception on /users [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1968, in finalize_request
    response = self.make_response(rv)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2098, in make_response
    "The view function did not return a valid response. The"
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2020-06-30 19:37:24,448 - werkzeug:113 - INFO - 127.0.0.1 - - [30/Jun/2020 19:37:24] "[35m[1mGET /users HTTP/1.1[0m" 500 -
2020-06-30 19:39:40,997 - werkzeug:113 - INFO -  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2020-06-30 19:39:59,860 - werkzeug:113 - INFO - 127.0.0.1 - - [30/Jun/2020 19:39:59] "[31m[1mPOST /users HTTP/1.1[0m" 400 -
2020-06-30 19:41:32,666 - werkzeug:113 - INFO -  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2020-06-30 19:41:40,301 - werkzeug:113 - INFO - 127.0.0.1 - - [30/Jun/2020 19:41:40] "[31m[1mPOST /users HTTP/1.1[0m" 400 -
2020-06-30 19:45:51,154 - werkzeug:113 - INFO -  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2020-06-30 19:46:01,812 - flask:1892 - ERROR - Exception on /users [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/user/Desktop/projectbackup/SchoolSystem/main.py", line 18, in login
    _log.debug(request.user)
  File "/usr/local/lib/python3.7/site-packages/werkzeug/local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
AttributeError: 'Request' object has no attribute 'user'
2020-06-30 19:46:01,818 - werkzeug:113 - INFO - 127.0.0.1 - - [30/Jun/2020 19:46:01] "[35m[1mPOST /users HTTP/1.1[0m" 500 -
2020-06-30 19:47:50,614 - flask:1892 - ERROR - Exception on /users [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/user/Desktop/projectbackup/SchoolSystem/main.py", line 18, in login
    _log.debug(request.user)
  File "/usr/local/lib/python3.7/site-packages/werkzeug/local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
AttributeError: 'Request' object has no attribute 'user'
2020-06-30 19:47:50,616 - werkzeug:113 - INFO - 127.0.0.1 - - [30/Jun/2020 19:47:50] "[35m[1mPOST /users HTTP/1.1[0m" 500 -
2020-06-30 19:48:43,690 - werkzeug:113 - INFO -  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2020-06-30 19:48:52,586 - flask:1892 - ERROR - Exception on /users [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/user/Desktop/projectbackup/SchoolSystem/main.py", line 18, in login
    _log.debug(request.body)
  File "/usr/local/lib/python3.7/site-packages/werkzeug/local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
AttributeError: 'Request' object has no attribute 'body'
2020-06-30 19:48:52,589 - werkzeug:113 - INFO - 127.0.0.1 - - [30/Jun/2020 19:48:52] "[35m[1mPOST /users HTTP/1.1[0m" 500 -
2020-06-30 19:50:13,551 - werkzeug:113 - INFO -  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2020-06-30 19:50:23,824 - SchoolSystem.data.mongo:23 - INFO - Attempting to retrieve user from database
2020-06-30 19:50:23,824 - flask:1892 - ERROR - Exception on /users [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/user/Desktop/projectbackup/SchoolSystem/main.py", line 20, in login
    user = db.login(request.json)
  File "/Users/user/Desktop/projectbackup/SchoolSystem/data/mongo.py", line 24, in login
    username = user.username
AttributeError: 'NoneType' object has no attribute 'username'
2020-06-30 19:50:23,835 - werkzeug:113 - INFO - 127.0.0.1 - - [30/Jun/2020 19:50:23] "[35m[1mPOST /users HTTP/1.1[0m" 500 -
2020-06-30 19:53:32,324 - werkzeug:113 - INFO -  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2020-06-30 19:53:40,808 - werkzeug:113 - INFO -  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2020-06-30 19:53:50,118 - flask:1892 - ERROR - Exception on /users [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/user/Desktop/projectbackup/SchoolSystem/main.py", line 18, in login
    _log.debug(req)
NameError: name 'req' is not defined
2020-06-30 19:53:50,122 - werkzeug:113 - INFO - 127.0.0.1 - - [30/Jun/2020 19:53:50] "[35m[1mPOST /users HTTP/1.1[0m" 500 -
2020-06-30 19:57:31,489 - werkzeug:113 - INFO -  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2020-06-30 19:57:45,364 - SchoolSystem.data.mongo:23 - INFO - Attempting to retrieve user from database
2020-06-30 19:57:45,365 - flask:1892 - ERROR - Exception on /users [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/user/Desktop/projectbackup/SchoolSystem/main.py", line 20, in login
    user = db.login(request.data)
  File "/Users/user/Desktop/projectbackup/SchoolSystem/data/mongo.py", line 24, in login
    username = user.username
AttributeError: 'bytes' object has no attribute 'username'
2020-06-30 19:57:45,375 - werkzeug:113 - INFO - 127.0.0.1 - - [30/Jun/2020 19:57:45] "[35m[1mPOST /users HTTP/1.1[0m" 500 -
2020-06-30 19:59:59,495 - werkzeug:113 - INFO -  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2020-06-30 20:00:06,844 - SchoolSystem.data.mongo:23 - INFO - Attempting to retrieve user from database
2020-06-30 20:00:06,844 - flask:1892 - ERROR - Exception on /users [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/user/Desktop/projectbackup/SchoolSystem/main.py", line 20, in login
    user = db.login(request.data)
  File "/Users/user/Desktop/projectbackup/SchoolSystem/data/mongo.py", line 24, in login
    username = user.username
AttributeError: 'bytes' object has no attribute 'username'
2020-06-30 20:00:06,846 - werkzeug:113 - INFO - 127.0.0.1 - - [30/Jun/2020 20:00:06] "[35m[1mPOST /users HTTP/1.1[0m" 500 -
2020-06-30 20:05:05,504 - werkzeug:113 - INFO -  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2020-06-30 20:05:11,963 - SchoolSystem.data.mongo:23 - INFO - Attempting to retrieve user from database
2020-06-30 20:05:11,964 - flask:1892 - ERROR - Exception on /users [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/user/Desktop/projectbackup/SchoolSystem/main.py", line 20, in login
    user = db.login(request.data)
  File "/Users/user/Desktop/projectbackup/SchoolSystem/data/mongo.py", line 24, in login
    username = user.username
AttributeError: 'bytes' object has no attribute 'username'
2020-06-30 20:05:11,966 - werkzeug:113 - INFO - 127.0.0.1 - - [30/Jun/2020 20:05:11] "[35m[1mPOST /users HTTP/1.1[0m" 500 -
2020-06-30 20:07:09,727 - werkzeug:113 - INFO -  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2020-06-30 20:07:17,425 - SchoolSystem.data.mongo:23 - INFO - Attempting to retrieve user from database
2020-06-30 20:07:17,425 - flask:1892 - ERROR - Exception on /users [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/user/Desktop/projectbackup/SchoolSystem/main.py", line 20, in login
    user = db.login(request.data)
  File "/Users/user/Desktop/projectbackup/SchoolSystem/data/mongo.py", line 24, in login
    username = user.username
AttributeError: 'bytes' object has no attribute 'username'
2020-06-30 20:07:17,428 - werkzeug:113 - INFO - 127.0.0.1 - - [30/Jun/2020 20:07:17] "[35m[1mPOST /users HTTP/1.1[0m" 500 -
2020-06-30 20:07:31,145 - SchoolSystem.data.mongo:23 - INFO - Attempting to retrieve user from database
2020-06-30 20:07:31,145 - flask:1892 - ERROR - Exception on /users [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/user/Desktop/projectbackup/SchoolSystem/main.py", line 20, in login
    user = db.login(request.data)
  File "/Users/user/Desktop/projectbackup/SchoolSystem/data/mongo.py", line 24, in login
    username = user.username
AttributeError: 'bytes' object has no attribute 'username'
2020-06-30 20:07:31,146 - werkzeug:113 - INFO - 127.0.0.1 - - [30/Jun/2020 20:07:31] "[35m[1mPOST /users HTTP/1.1[0m" 500 -
2020-06-30 20:09:06,536 - werkzeug:113 - INFO -  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2020-06-30 20:09:12,872 - werkzeug:113 - INFO - 127.0.0.1 - - [30/Jun/2020 20:09:12] "[37mOPTIONS /users HTTP/1.1[0m" 200 -
2020-06-30 20:09:12,874 - SchoolSystem.data.mongo:23 - INFO - Attempting to retrieve user from database
2020-06-30 20:09:12,874 - flask:1892 - ERROR - Exception on /users [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/user/Desktop/projectbackup/SchoolSystem/main.py", line 20, in login
    user = db.login(request.data)
  File "/Users/user/Desktop/projectbackup/SchoolSystem/data/mongo.py", line 24, in login
    username = user.username
AttributeError: 'bytes' object has no attribute 'username'
2020-06-30 20:09:12,885 - werkzeug:113 - INFO - 127.0.0.1 - - [30/Jun/2020 20:09:12] "[35m[1mPOST /users HTTP/1.1[0m" 500 -
2020-06-30 20:12:59,662 - werkzeug:113 - INFO -  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2020-06-30 20:13:07,009 - werkzeug:113 - INFO - 127.0.0.1 - - [30/Jun/2020 20:13:07] "[37mOPTIONS /users HTTP/1.1[0m" 200 -
2020-06-30 20:13:07,011 - SchoolSystem.data.mongo:23 - INFO - Attempting to retrieve user from database
2020-06-30 20:13:07,012 - flask:1892 - ERROR - Exception on /users [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/user/Desktop/projectbackup/SchoolSystem/main.py", line 20, in login
    user = db.login(request.data.decode('utf-8'))
  File "/Users/user/Desktop/projectbackup/SchoolSystem/data/mongo.py", line 24, in login
    username = user.username
AttributeError: 'str' object has no attribute 'username'
2020-06-30 20:13:07,024 - werkzeug:113 - INFO - 127.0.0.1 - - [30/Jun/2020 20:13:07] "[35m[1mPOST /users HTTP/1.1[0m" 500 -
2020-06-30 20:15:32,063 - werkzeug:113 - INFO -  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2020-06-30 20:15:37,936 - werkzeug:113 - INFO - 127.0.0.1 - - [30/Jun/2020 20:15:37] "[37mOPTIONS /users HTTP/1.1[0m" 200 -
2020-06-30 20:15:37,938 - SchoolSystem.data.mongo:23 - INFO - Attempting to retrieve user from database
2020-06-30 20:15:37,938 - flask:1892 - ERROR - Exception on /users [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/user/Desktop/projectbackup/SchoolSystem/main.py", line 21, in login
    user = db.login(temp)
  File "/Users/user/Desktop/projectbackup/SchoolSystem/data/mongo.py", line 24, in login
    username = user.username
AttributeError: 'Response' object has no attribute 'username'
2020-06-30 20:15:37,945 - werkzeug:113 - INFO - 127.0.0.1 - - [30/Jun/2020 20:15:37] "[35m[1mPOST /users HTTP/1.1[0m" 500 -
2020-06-30 20:17:10,680 - werkzeug:113 - INFO -  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2020-06-30 20:17:16,795 - werkzeug:113 - INFO - 127.0.0.1 - - [30/Jun/2020 20:17:16] "[37mOPTIONS /users HTTP/1.1[0m" 200 -
2020-06-30 20:17:16,797 - flask:1892 - ERROR - Exception on /users [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/user/Desktop/projectbackup/SchoolSystem/main.py", line 20, in login
    vary = temp['username']
TypeError: 'Response' object is not subscriptable
2020-06-30 20:17:16,804 - werkzeug:113 - INFO - 127.0.0.1 - - [30/Jun/2020 20:17:16] "[35m[1mPOST /users HTTP/1.1[0m" 500 -
2020-06-30 20:18:31,344 - werkzeug:113 - INFO - 127.0.0.1 - - [30/Jun/2020 20:18:31] "[37mOPTIONS /users HTTP/1.1[0m" 200 -
2020-06-30 20:18:31,347 - flask:1892 - ERROR - Exception on /users [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/user/Desktop/projectbackup/SchoolSystem/main.py", line 20, in login
    vary = temp['username']
TypeError: 'Response' object is not subscriptable
2020-06-30 20:18:31,354 - werkzeug:113 - INFO - 127.0.0.1 - - [30/Jun/2020 20:18:31] "[35m[1mPOST /users HTTP/1.1[0m" 500 -
2020-06-30 20:19:18,864 - werkzeug:113 - INFO -  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2020-06-30 20:19:25,935 - werkzeug:113 - INFO - 127.0.0.1 - - [30/Jun/2020 20:19:25] "[37mOPTIONS /users HTTP/1.1[0m" 200 -
2020-06-30 20:19:25,938 - SchoolSystem.data.mongo:23 - INFO - Attempting to retrieve user from database
2020-06-30 20:19:25,938 - flask:1892 - ERROR - Exception on /users [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/user/Desktop/projectbackup/SchoolSystem/main.py", line 21, in login
    user = db.login(temp)
  File "/Users/user/Desktop/projectbackup/SchoolSystem/data/mongo.py", line 24, in login
    username = user.username
AttributeError: 'Response' object has no attribute 'username'
2020-06-30 20:19:25,947 - werkzeug:113 - INFO - 127.0.0.1 - - [30/Jun/2020 20:19:25] "[35m[1mPOST /users HTTP/1.1[0m" 500 -
2020-06-30 20:21:22,522 - werkzeug:113 - INFO -  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2020-06-30 20:21:28,496 - werkzeug:113 - INFO - 127.0.0.1 - - [30/Jun/2020 20:21:28] "[37mOPTIONS /users HTTP/1.1[0m" 200 -
2020-06-30 20:21:28,498 - SchoolSystem.data.mongo:23 - INFO - Attempting to retrieve user from database
2020-06-30 20:21:28,498 - flask:1892 - ERROR - Exception on /users [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/user/Desktop/projectbackup/SchoolSystem/main.py", line 21, in login
    user = db.login(temp)
  File "/Users/user/Desktop/projectbackup/SchoolSystem/data/mongo.py", line 24, in login
    username = user.username
AttributeError: 'str' object has no attribute 'username'
2020-06-30 20:21:28,506 - werkzeug:113 - INFO - 127.0.0.1 - - [30/Jun/2020 20:21:28] "[35m[1mPOST /users HTTP/1.1[0m" 500 -
2020-06-30 20:23:48,627 - werkzeug:113 - INFO -  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2020-06-30 20:23:55,178 - werkzeug:113 - INFO - 127.0.0.1 - - [30/Jun/2020 20:23:55] "[37mOPTIONS /users HTTP/1.1[0m" 200 -
2020-06-30 20:23:55,181 - flask:1892 - ERROR - Exception on /users [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/user/Desktop/projectbackup/SchoolSystem/main.py", line 20, in login
    _log.debug(temp.__dict__)
AttributeError: 'str' object has no attribute '__dict__'
2020-06-30 20:23:55,188 - werkzeug:113 - INFO - 127.0.0.1 - - [30/Jun/2020 20:23:55] "[35m[1mPOST /users HTTP/1.1[0m" 500 -
2020-06-30 20:25:25,356 - werkzeug:113 - INFO -  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2020-06-30 20:25:31,752 - werkzeug:113 - INFO - 127.0.0.1 - - [30/Jun/2020 20:25:31] "[37mOPTIONS /users HTTP/1.1[0m" 200 -
2020-06-30 20:25:31,755 - SchoolSystem.data.mongo:23 - INFO - Attempting to retrieve user from database
2020-06-30 20:25:31,755 - flask:1892 - ERROR - Exception on /users [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/user/Desktop/projectbackup/SchoolSystem/main.py", line 21, in login
    user = db.login(temp)
  File "/Users/user/Desktop/projectbackup/SchoolSystem/data/mongo.py", line 24, in login
    username = user.username
AttributeError: 'bytes' object has no attribute 'username'
2020-06-30 20:25:31,763 - werkzeug:113 - INFO - 127.0.0.1 - - [30/Jun/2020 20:25:31] "[35m[1mPOST /users HTTP/1.1[0m" 500 -
2020-06-30 20:27:09,974 - werkzeug:113 - INFO -  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2020-06-30 20:27:19,232 - werkzeug:113 - INFO - 127.0.0.1 - - [30/Jun/2020 20:27:19] "[37mOPTIONS /users HTTP/1.1[0m" 200 -
2020-06-30 20:27:19,234 - SchoolSystem.data.mongo:23 - INFO - Attempting to retrieve user from database
2020-06-30 20:27:19,235 - flask:1892 - ERROR - Exception on /users [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/user/Desktop/projectbackup/SchoolSystem/main.py", line 21, in login
    user = db.login(temp.__dict__)
  File "/Users/user/Desktop/projectbackup/SchoolSystem/data/mongo.py", line 24, in login
    username = user.username
AttributeError: 'dict' object has no attribute 'username'
2020-06-30 20:27:19,243 - werkzeug:113 - INFO - 127.0.0.1 - - [30/Jun/2020 20:27:19] "[35m[1mPOST /users HTTP/1.1[0m" 500 -
2020-06-30 20:29:32,081 - werkzeug:113 - INFO -  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2020-06-30 20:29:44,583 - werkzeug:113 - INFO - 127.0.0.1 - - [30/Jun/2020 20:29:44] "[37mOPTIONS /users HTTP/1.1[0m" 200 -
2020-06-30 20:29:44,587 - flask:1892 - ERROR - Exception on /users [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/user/Desktop/projectbackup/SchoolSystem/main.py", line 18, in login
    _log.debug(jsonify(request.form.decode('utf-8')))
AttributeError: 'ImmutableMultiDict' object has no attribute 'decode'
2020-06-30 20:29:44,593 - werkzeug:113 - INFO - 127.0.0.1 - - [30/Jun/2020 20:29:44] "[35m[1mPOST /users HTTP/1.1[0m" 500 -
2020-06-30 20:30:27,878 - werkzeug:113 - INFO -  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2020-06-30 20:30:34,967 - werkzeug:113 - INFO - 127.0.0.1 - - [30/Jun/2020 20:30:34] "[37mOPTIONS /users HTTP/1.1[0m" 200 -
2020-06-30 20:30:34,970 - SchoolSystem.data.mongo:23 - INFO - Attempting to retrieve user from database
2020-06-30 20:30:34,970 - flask:1892 - ERROR - Exception on /users [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/user/Desktop/projectbackup/SchoolSystem/main.py", line 21, in login
    user = db.login(temp.__dict__)
  File "/Users/user/Desktop/projectbackup/SchoolSystem/data/mongo.py", line 24, in login
    username = user.username
AttributeError: 'dict' object has no attribute 'username'
2020-06-30 20:30:34,977 - werkzeug:113 - INFO - 127.0.0.1 - - [30/Jun/2020 20:30:34] "[35m[1mPOST /users HTTP/1.1[0m" 500 -
2020-06-30 20:39:35,436 - werkzeug:113 - INFO -  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2020-06-30 20:39:45,953 - werkzeug:113 - INFO - 127.0.0.1 - - [30/Jun/2020 20:39:45] "[37mOPTIONS /users HTTP/1.1[0m" 200 -
2020-06-30 20:39:45,955 - flask:1892 - ERROR - Exception on /users [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/user/Desktop/projectbackup/SchoolSystem/main.py", line 18, in login
    _log.debug((request.form.get_json()))
AttributeError: 'ImmutableMultiDict' object has no attribute 'get_json'
2020-06-30 20:39:45,963 - werkzeug:113 - INFO - 127.0.0.1 - - [30/Jun/2020 20:39:45] "[35m[1mPOST /users HTTP/1.1[0m" 500 -
2020-06-30 20:40:53,119 - werkzeug:113 - INFO -  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2020-06-30 20:41:03,773 - werkzeug:113 - INFO - 127.0.0.1 - - [30/Jun/2020 20:41:03] "[37mOPTIONS /users HTTP/1.1[0m" 200 -
2020-06-30 20:41:03,776 - flask:1892 - ERROR - Exception on /users [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/user/Desktop/projectbackup/SchoolSystem/main.py", line 20, in login
    _log.debug(temp.__dict__)
AttributeError: 'str' object has no attribute '__dict__'
2020-06-30 20:41:03,783 - werkzeug:113 - INFO - 127.0.0.1 - - [30/Jun/2020 20:41:03] "[35m[1mPOST /users HTTP/1.1[0m" 500 -
2020-06-30 20:41:39,842 - werkzeug:113 - INFO -  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2020-06-30 20:41:49,502 - werkzeug:113 - INFO - 127.0.0.1 - - [30/Jun/2020 20:41:49] "[37mOPTIONS /users HTTP/1.1[0m" 200 -
2020-06-30 20:41:49,505 - SchoolSystem.data.mongo:23 - INFO - Attempting to retrieve user from database
2020-06-30 20:41:49,505 - flask:1892 - ERROR - Exception on /users [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/user/Desktop/projectbackup/SchoolSystem/main.py", line 21, in login
    user = db.login(temp)
  File "/Users/user/Desktop/projectbackup/SchoolSystem/data/mongo.py", line 24, in login
    username = user.username
AttributeError: 'str' object has no attribute 'username'
2020-06-30 20:41:49,512 - werkzeug:113 - INFO - 127.0.0.1 - - [30/Jun/2020 20:41:49] "[35m[1mPOST /users HTTP/1.1[0m" 500 -
2020-06-30 20:43:09,955 - werkzeug:113 - INFO -  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2020-06-30 20:43:18,455 - werkzeug:113 - INFO - 127.0.0.1 - - [30/Jun/2020 20:43:18] "[37mOPTIONS /users HTTP/1.1[0m" 200 -
2020-06-30 20:43:18,464 - werkzeug:113 - INFO - 127.0.0.1 - - [30/Jun/2020 20:43:18] "[31m[1mPOST /users HTTP/1.1[0m" 400 -
2020-06-30 20:45:11,412 - werkzeug:113 - INFO -  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2020-06-30 20:45:30,668 - werkzeug:113 - INFO -  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2020-06-30 20:45:39,400 - werkzeug:113 - INFO - 127.0.0.1 - - [30/Jun/2020 20:45:39] "[37mOPTIONS /users HTTP/1.1[0m" 200 -
2020-06-30 20:45:39,403 - werkzeug:113 - INFO - 127.0.0.1 - - [30/Jun/2020 20:45:39] "[31m[1mPOST /users HTTP/1.1[0m" 400 -
2020-06-30 20:46:44,784 - werkzeug:113 - INFO - 127.0.0.1 - - [30/Jun/2020 20:46:44] "[31m[1mPOST /users HTTP/1.1[0m" 400 -
2020-06-30 20:48:10,561 - werkzeug:113 - INFO -  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2020-06-30 20:48:21,573 - werkzeug:113 - INFO - 127.0.0.1 - - [30/Jun/2020 20:48:21] "[37mOPTIONS /users HTTP/1.1[0m" 200 -
2020-06-30 20:48:21,575 - SchoolSystem.data.mongo:23 - INFO - Attempting to retrieve user from database
2020-06-30 20:48:21,576 - flask:1892 - ERROR - Exception on /users [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/user/Desktop/projectbackup/SchoolSystem/main.py", line 22, in login
    user = db.login(temp)
  File "/Users/user/Desktop/projectbackup/SchoolSystem/data/mongo.py", line 24, in login
    username = user.username
AttributeError: 'NoneType' object has no attribute 'username'
2020-06-30 20:48:21,583 - werkzeug:113 - INFO - 127.0.0.1 - - [30/Jun/2020 20:48:21] "[35m[1mPOST /users HTTP/1.1[0m" 500 -
2020-07-01 13:58:10,714 - werkzeug:113 - INFO -  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2020-07-01 13:58:25,221 - werkzeug:113 - INFO - 127.0.0.1 - - [01/Jul/2020 13:58:25] "[37mOPTIONS /users HTTP/1.1[0m" 200 -
2020-07-01 13:58:25,223 - SchoolSystem.data.mongo:23 - INFO - Attempting to retrieve user from database
2020-07-01 13:58:25,223 - flask:1892 - ERROR - Exception on /users [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/user/Desktop/projectbackup/SchoolSystem/main.py", line 22, in login
    user = db.login(temp)
  File "/Users/user/Desktop/projectbackup/SchoolSystem/data/mongo.py", line 24, in login
    username = user.username
AttributeError: 'NoneType' object has no attribute 'username'
2020-07-01 13:58:25,232 - werkzeug:113 - INFO - 127.0.0.1 - - [01/Jul/2020 13:58:25] "[35m[1mPOST /users HTTP/1.1[0m" 500 -
2020-07-01 16:32:31,082 - werkzeug:113 - INFO -  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2020-07-01 16:32:42,747 - werkzeug:113 - INFO - 127.0.0.1 - - [01/Jul/2020 16:32:42] "[37mOPTIONS /users HTTP/1.1[0m" 200 -
2020-07-01 16:32:42,750 - SchoolSystem.data.mongo:23 - INFO - Attempting to retrieve user from database
2020-07-01 16:32:42,751 - flask:1892 - ERROR - Exception on /users [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/user/Desktop/projectbackup/SchoolSystem/main.py", line 22, in login
    user = db.login(temp)
  File "/Users/user/Desktop/projectbackup/SchoolSystem/data/mongo.py", line 24, in login
    username = user.username
AttributeError: 'NoneType' object has no attribute 'username'
2020-07-01 16:32:42,756 - werkzeug:113 - INFO - 127.0.0.1 - - [01/Jul/2020 16:32:42] "[35m[1mPOST /users HTTP/1.1[0m" 500 -
2020-07-01 16:35:02,481 - werkzeug:113 - INFO -  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2020-07-01 16:35:09,880 - werkzeug:113 - INFO - 127.0.0.1 - - [01/Jul/2020 16:35:09] "[37mOPTIONS /users HTTP/1.1[0m" 200 -
2020-07-01 16:35:09,883 - SchoolSystem.data.mongo:23 - INFO - Attempting to retrieve user from database
2020-07-01 16:35:09,883 - flask:1892 - ERROR - Exception on /users [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/user/Desktop/projectbackup/SchoolSystem/main.py", line 22, in login
    user = db.login(temp)
  File "/Users/user/Desktop/projectbackup/SchoolSystem/data/mongo.py", line 24, in login
    username = user.username
AttributeError: 'str' object has no attribute 'username'
2020-07-01 16:35:09,893 - werkzeug:113 - INFO - 127.0.0.1 - - [01/Jul/2020 16:35:09] "[35m[1mPOST /users HTTP/1.1[0m" 500 -
2020-07-01 16:36:36,891 - werkzeug:113 - INFO -  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2020-07-01 16:36:43,703 - werkzeug:113 - INFO - 127.0.0.1 - - [01/Jul/2020 16:36:43] "[37mOPTIONS /users HTTP/1.1[0m" 200 -
2020-07-01 16:36:43,706 - SchoolSystem.data.mongo:23 - INFO - Attempting to retrieve user from database
2020-07-01 16:36:43,707 - flask:1892 - ERROR - Exception on /users [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/user/Desktop/projectbackup/SchoolSystem/main.py", line 22, in login
    user = db.login(temp)
  File "/Users/user/Desktop/projectbackup/SchoolSystem/data/mongo.py", line 24, in login
    username = user.username
NameError: name 'user' is not defined
2020-07-01 16:36:43,714 - werkzeug:113 - INFO - 127.0.0.1 - - [01/Jul/2020 16:36:43] "[35m[1mPOST /users HTTP/1.1[0m" 500 -
2020-07-01 16:36:59,569 - werkzeug:113 - INFO -  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2020-07-01 16:37:08,608 - werkzeug:113 - INFO - 127.0.0.1 - - [01/Jul/2020 16:37:08] "[37mOPTIONS /users HTTP/1.1[0m" 200 -
2020-07-01 16:37:08,610 - SchoolSystem.data.mongo:23 - INFO - Attempting to retrieve user from database
2020-07-01 16:37:08,841 - flask:1892 - ERROR - Exception on /users [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/user/Desktop/projectbackup/SchoolSystem/main.py", line 30, in login
    return response, 200
NameError: name 'response' is not defined
2020-07-01 16:37:08,843 - werkzeug:113 - INFO - 127.0.0.1 - - [01/Jul/2020 16:37:08] "[35m[1mPOST /users HTTP/1.1[0m" 500 -
2020-07-01 16:38:00,260 - werkzeug:113 - INFO -  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2020-07-01 16:38:07,989 - werkzeug:113 - INFO - 127.0.0.1 - - [01/Jul/2020 16:38:07] "[37mOPTIONS /users HTTP/1.1[0m" 200 -
2020-07-01 16:38:07,992 - SchoolSystem.data.mongo:23 - INFO - Attempting to retrieve user from database
2020-07-01 16:38:08,193 - flask:1892 - ERROR - Exception on /users [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1968, in finalize_request
    response = self.make_response(rv)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2131, in make_response
    " {rv.__class__.__name__}.".format(rv=rv)
TypeError: The view function did not return a valid response. The return type must be a string, dict, tuple, Response instance, or WSGI callable, but it was a User.
2020-07-01 16:38:08,195 - werkzeug:113 - INFO - 127.0.0.1 - - [01/Jul/2020 16:38:08] "[35m[1mPOST /users HTTP/1.1[0m" 500 -
2020-07-01 16:38:53,603 - werkzeug:113 - INFO -  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2020-07-01 16:39:01,161 - werkzeug:113 - INFO - 127.0.0.1 - - [01/Jul/2020 16:39:01] "[37mOPTIONS /users HTTP/1.1[0m" 200 -
2020-07-01 16:39:01,164 - SchoolSystem.data.mongo:23 - INFO - Attempting to retrieve user from database
2020-07-01 16:39:01,355 - flask:1892 - ERROR - Exception on /users [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1968, in finalize_request
    response = self.make_response(rv)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2112, in make_response
    rv = jsonify(rv)
  File "/usr/local/lib/python3.7/site-packages/flask/json/__init__.py", line 370, in jsonify
    dumps(data, indent=indent, separators=separators) + "\n",
  File "/usr/local/lib/python3.7/site-packages/flask/json/__init__.py", line 211, in dumps
    rv = _json.dumps(obj, **kwargs)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.7/site-packages/flask/json/__init__.py", line 100, in default
    return _json.JSONEncoder.default(self, o)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ObjectId is not JSON serializable
2020-07-01 16:39:01,365 - werkzeug:113 - INFO - 127.0.0.1 - - [01/Jul/2020 16:39:01] "[35m[1mPOST /users HTTP/1.1[0m" 500 -
2020-07-01 16:49:27,074 - werkzeug:113 - INFO -  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2020-07-01 16:49:37,160 - werkzeug:113 - INFO - 127.0.0.1 - - [01/Jul/2020 16:49:37] "[37mOPTIONS /users HTTP/1.1[0m" 200 -
2020-07-01 16:49:37,163 - SchoolSystem.data.mongo:23 - INFO - Attempting to retrieve user from database
2020-07-01 16:49:37,367 - werkzeug:113 - INFO - 127.0.0.1 - - [01/Jul/2020 16:49:37] "[31m[1mPOST /users HTTP/1.1[0m" 401 -
2020-07-01 16:51:35,844 - werkzeug:113 - INFO -  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2020-07-01 16:51:42,671 - werkzeug:113 - INFO - 127.0.0.1 - - [01/Jul/2020 16:51:42] "[37mOPTIONS /users HTTP/1.1[0m" 200 -
2020-07-01 16:51:42,674 - SchoolSystem.data.mongo:23 - INFO - Attempting to retrieve user from database
2020-07-01 16:51:42,867 - werkzeug:113 - INFO - 127.0.0.1 - - [01/Jul/2020 16:51:42] "[31m[1mPOST /users HTTP/1.1[0m" 401 -
2020-07-01 16:53:17,919 - werkzeug:113 - INFO -  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2020-07-01 16:53:24,356 - werkzeug:113 - INFO - 127.0.0.1 - - [01/Jul/2020 16:53:24] "[37mOPTIONS /users HTTP/1.1[0m" 200 -
2020-07-01 16:53:24,358 - SchoolSystem.data.mongo:23 - INFO - Attempting to retrieve user from database
2020-07-01 16:53:24,543 - werkzeug:113 - INFO - 127.0.0.1 - - [01/Jul/2020 16:53:24] "[31m[1mPOST /users HTTP/1.1[0m" 401 -
2020-07-01 16:54:12,378 - werkzeug:113 - INFO - 127.0.0.1 - - [01/Jul/2020 16:54:12] "[37mOPTIONS /users HTTP/1.1[0m" 200 -
2020-07-01 16:54:12,381 - SchoolSystem.data.mongo:23 - INFO - Attempting to retrieve user from database
2020-07-01 16:54:12,399 - werkzeug:113 - INFO - 127.0.0.1 - - [01/Jul/2020 16:54:12] "[31m[1mPOST /users HTTP/1.1[0m" 401 -
2020-07-01 16:57:11,797 - werkzeug:113 - INFO -  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2020-07-01 16:57:20,324 - werkzeug:113 - INFO - 127.0.0.1 - - [01/Jul/2020 16:57:20] "[37mOPTIONS /users HTTP/1.1[0m" 200 -
2020-07-01 16:57:20,326 - SchoolSystem.data.mongo:23 - INFO - Attempting to retrieve user from database
2020-07-01 16:57:20,575 - werkzeug:113 - INFO - 127.0.0.1 - - [01/Jul/2020 16:57:20] "[37mPOST /users HTTP/1.1[0m" 200 -
2020-07-01 16:58:04,578 - werkzeug:113 - INFO -  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2020-07-01 16:58:26,549 - werkzeug:113 - INFO - 127.0.0.1 - - [01/Jul/2020 16:58:26] "[37mOPTIONS /users HTTP/1.1[0m" 200 -
2020-07-01 16:58:26,551 - SchoolSystem.data.mongo:23 - INFO - Attempting to retrieve user from database
2020-07-01 16:58:26,731 - werkzeug:113 - INFO - 127.0.0.1 - - [01/Jul/2020 16:58:26] "[37mPOST /users HTTP/1.1[0m" 200 -
2020-07-01 16:59:17,232 - werkzeug:113 - INFO - 127.0.0.1 - - [01/Jul/2020 16:59:17] "[37mOPTIONS /users HTTP/1.1[0m" 200 -
2020-07-01 16:59:17,235 - SchoolSystem.data.mongo:23 - INFO - Attempting to retrieve user from database
2020-07-01 16:59:17,254 - werkzeug:113 - INFO - 127.0.0.1 - - [01/Jul/2020 16:59:17] "[37mPOST /users HTTP/1.1[0m" 200 -
2020-07-01 17:05:49,390 - werkzeug:113 - INFO - 127.0.0.1 - - [01/Jul/2020 17:05:49] "[37mOPTIONS /users HTTP/1.1[0m" 200 -
2020-07-01 17:05:49,396 - SchoolSystem.data.mongo:23 - INFO - Attempting to retrieve user from database
2020-07-01 17:05:49,424 - werkzeug:113 - INFO - 127.0.0.1 - - [01/Jul/2020 17:05:49] "[31m[1mPOST /users HTTP/1.1[0m" 401 -
2020-07-01 17:06:27,945 - werkzeug:113 - INFO - 127.0.0.1 - - [01/Jul/2020 17:06:27] "[37mOPTIONS /users HTTP/1.1[0m" 200 -
2020-07-01 17:06:27,948 - SchoolSystem.data.mongo:23 - INFO - Attempting to retrieve user from database
2020-07-01 17:06:28,031 - werkzeug:113 - INFO - 127.0.0.1 - - [01/Jul/2020 17:06:28] "[31m[1mPOST /users HTTP/1.1[0m" 401 -
2020-07-01 17:13:14,696 - flask:1892 - ERROR - Exception on /users [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1968, in finalize_request
    response = self.make_response(rv)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2098, in make_response
    "The view function did not return a valid response. The"
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2020-07-01 17:13:14,699 - werkzeug:113 - INFO - 127.0.0.1 - - [01/Jul/2020 17:13:14] "[35m[1mGET /users HTTP/1.1[0m" 500 -
2020-07-01 17:21:53,055 - flask:1892 - ERROR - Exception on /users [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1968, in finalize_request
    response = self.make_response(rv)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2098, in make_response
    "The view function did not return a valid response. The"
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2020-07-01 17:21:53,057 - werkzeug:113 - INFO - 127.0.0.1 - - [01/Jul/2020 17:21:53] "[35m[1mGET /users HTTP/1.1[0m" 500 -
2020-07-01 17:29:57,199 - werkzeug:113 - INFO - 127.0.0.1 - - [01/Jul/2020 17:29:57] "[37mOPTIONS /users HTTP/1.1[0m" 200 -
2020-07-01 17:29:57,202 - flask:1892 - ERROR - Exception on /users [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/user/Desktop/projectbackup/SchoolSystem/main.py", line 19, in login
    _log.debug(request.json['username'])
KeyError: 'username'
2020-07-01 17:29:57,205 - werkzeug:113 - INFO - 127.0.0.1 - - [01/Jul/2020 17:29:57] "[35m[1mPOST /users HTTP/1.1[0m" 500 -
2020-07-01 17:31:22,311 - werkzeug:113 - INFO -  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2020-07-01 17:31:29,414 - werkzeug:113 - INFO - 127.0.0.1 - - [01/Jul/2020 17:31:29] "[37mOPTIONS /users HTTP/1.1[0m" 200 -
2020-07-01 17:31:29,416 - flask:1892 - ERROR - Exception on /users [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/user/Desktop/projectbackup/SchoolSystem/main.py", line 19, in login
    _log.debug(request.json['username'])
KeyError: 'username'
2020-07-01 17:31:29,420 - werkzeug:113 - INFO - 127.0.0.1 - - [01/Jul/2020 17:31:29] "[35m[1mPOST /users HTTP/1.1[0m" 500 -
2020-07-01 17:33:33,638 - werkzeug:113 - INFO -  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2020-07-01 17:36:13,169 - werkzeug:113 - INFO - 127.0.0.1 - - [01/Jul/2020 17:36:13] "[37mOPTIONS /users HTTP/1.1[0m" 200 -
2020-07-01 17:36:13,172 - SchoolSystem.data.mongo:23 - INFO - Attempting to retrieve user from database
2020-07-01 17:36:13,376 - werkzeug:113 - INFO - 127.0.0.1 - - [01/Jul/2020 17:36:13] "[37mPOST /users HTTP/1.1[0m" 200 -
2020-07-01 17:38:04,625 - werkzeug:113 - INFO - 127.0.0.1 - - [01/Jul/2020 17:38:04] "[37mOPTIONS /users HTTP/1.1[0m" 200 -
2020-07-01 17:38:04,629 - SchoolSystem.data.mongo:23 - INFO - Attempting to retrieve user from database
2020-07-01 17:38:04,652 - werkzeug:113 - INFO - 127.0.0.1 - - [01/Jul/2020 17:38:04] "[37mPOST /users HTTP/1.1[0m" 200 -
2020-07-01 17:38:41,825 - werkzeug:113 - INFO - 127.0.0.1 - - [01/Jul/2020 17:38:41] "[37mOPTIONS /users HTTP/1.1[0m" 200 -
2020-07-01 17:38:41,830 - SchoolSystem.data.mongo:23 - INFO - Attempting to retrieve user from database
2020-07-01 17:38:41,857 - werkzeug:113 - INFO - 127.0.0.1 - - [01/Jul/2020 17:38:41] "[37mPOST /users HTTP/1.1[0m" 200 -
2020-07-01 17:39:06,933 - werkzeug:113 - INFO - 127.0.0.1 - - [01/Jul/2020 17:39:06] "[37mOPTIONS /users HTTP/1.1[0m" 200 -
2020-07-01 17:39:06,936 - SchoolSystem.data.mongo:23 - INFO - Attempting to retrieve user from database
2020-07-01 17:39:06,965 - werkzeug:113 - INFO - 127.0.0.1 - - [01/Jul/2020 17:39:06] "[37mPOST /users HTTP/1.1[0m" 200 -
2020-07-01 17:39:53,823 - werkzeug:113 - INFO - 127.0.0.1 - - [01/Jul/2020 17:39:53] "[37mOPTIONS /users HTTP/1.1[0m" 200 -
2020-07-01 17:39:53,825 - SchoolSystem.data.mongo:23 - INFO - Attempting to retrieve user from database
2020-07-01 17:39:53,844 - werkzeug:113 - INFO - 127.0.0.1 - - [01/Jul/2020 17:39:53] "[37mPOST /users HTTP/1.1[0m" 200 -
2020-07-01 18:02:42,195 - werkzeug:113 - INFO -  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2020-07-01 18:04:15,581 - flask:1892 - ERROR - Exception on /users [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/user/Desktop/projectbackup/SchoolSystem/main.py", line 19, in login
    _log.debug(request.json['username'])
TypeError: 'NoneType' object is not subscriptable
2020-07-01 18:04:15,585 - werkzeug:113 - INFO - 127.0.0.1 - - [01/Jul/2020 18:04:15] "[35m[1mPOST /users HTTP/1.1[0m" 500 -
2020-07-01 18:04:45,975 - flask:1892 - ERROR - Exception on /users [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1968, in finalize_request
    response = self.make_response(rv)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2098, in make_response
    "The view function did not return a valid response. The"
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2020-07-01 18:04:45,976 - werkzeug:113 - INFO - 127.0.0.1 - - [01/Jul/2020 18:04:45] "[35m[1mGET /users HTTP/1.1[0m" 500 -
2020-07-01 18:22:10,312 - werkzeug:113 - INFO -  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2020-07-01 18:22:53,120 - werkzeug:113 - INFO - 127.0.0.1 - - [01/Jul/2020 18:22:53] "[37mOPTIONS /users HTTP/1.1[0m" 200 -
2020-07-01 18:22:53,123 - SchoolSystem.data.mongo:23 - INFO - Attempting to retrieve user from database
2020-07-01 18:22:53,411 - werkzeug:113 - INFO - 127.0.0.1 - - [01/Jul/2020 18:22:53] "[37mPOST /users HTTP/1.1[0m" 200 -
2020-07-01 18:26:28,947 - werkzeug:113 - INFO - 127.0.0.1 - - [01/Jul/2020 18:26:28] "[37mOPTIONS /users HTTP/1.1[0m" 200 -
2020-07-01 18:26:28,950 - SchoolSystem.data.mongo:23 - INFO - Attempting to retrieve user from database
2020-07-01 18:26:28,976 - werkzeug:113 - INFO - 127.0.0.1 - - [01/Jul/2020 18:26:28] "[37mPOST /users HTTP/1.1[0m" 200 -
2020-07-01 18:27:03,615 - werkzeug:113 - INFO - 127.0.0.1 - - [01/Jul/2020 18:27:03] "[37mOPTIONS /users HTTP/1.1[0m" 200 -
2020-07-01 18:27:03,617 - SchoolSystem.data.mongo:23 - INFO - Attempting to retrieve user from database
2020-07-01 18:27:03,640 - werkzeug:113 - INFO - 127.0.0.1 - - [01/Jul/2020 18:27:03] "[37mPOST /users HTTP/1.1[0m" 200 -
2020-07-01 18:37:17,259 - werkzeug:113 - INFO - 127.0.0.1 - - [01/Jul/2020 18:37:17] "[37mOPTIONS /users HTTP/1.1[0m" 200 -
2020-07-01 18:37:17,264 - SchoolSystem.data.mongo:23 - INFO - Attempting to retrieve user from database
2020-07-01 18:37:17,284 - werkzeug:113 - INFO - 127.0.0.1 - - [01/Jul/2020 18:37:17] "[37mPOST /users HTTP/1.1[0m" 200 -
2020-07-01 18:37:42,267 - werkzeug:113 - INFO - 127.0.0.1 - - [01/Jul/2020 18:37:42] "[37mOPTIONS /users HTTP/1.1[0m" 200 -
2020-07-01 18:37:42,270 - SchoolSystem.data.mongo:23 - INFO - Attempting to retrieve user from database
2020-07-01 18:37:42,292 - werkzeug:113 - INFO - 127.0.0.1 - - [01/Jul/2020 18:37:42] "[37mPOST /users HTTP/1.1[0m" 200 -
2020-07-07 20:41:50,109 - werkzeug:113 - INFO -  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2020-07-07 20:44:01,776 - werkzeug:113 - INFO - 127.0.0.1 - - [07/Jul/2020 20:44:01] "[37mOPTIONS /users HTTP/1.1[0m" 200 -
2020-07-07 20:44:02,027 - SchoolSystem.data.mongo:23 - INFO - Attempting to retrieve user from database
2020-07-07 20:44:02,552 - werkzeug:113 - INFO - 127.0.0.1 - - [07/Jul/2020 20:44:02] "[37mPOST /users HTTP/1.1[0m" 200 -
2020-07-07 20:44:03,391 - __main__:1891 - ERROR - Exception on /users [DELETE]
Traceback (most recent call last):
  File "c:\users\alcar\revature\schoolsystem\schoolsystem\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\alcar\revature\schoolsystem\schoolsystem\lib\site-packages\flask\app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "c:\users\alcar\revature\schoolsystem\schoolsystem\lib\site-packages\flask\app.py", line 1968, in finalize_request
    response = self.make_response(rv)
  File "c:\users\alcar\revature\schoolsystem\schoolsystem\lib\site-packages\flask\app.py", line 2097, in make_response
    raise TypeError(
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2020-07-07 20:44:03,410 - werkzeug:113 - INFO - 127.0.0.1 - - [07/Jul/2020 20:44:03] "[35m[1mDELETE /users HTTP/1.1[0m" 500 -
2020-07-07 20:44:05,448 - __main__:1891 - ERROR - Exception on /users [DELETE]
Traceback (most recent call last):
  File "c:\users\alcar\revature\schoolsystem\schoolsystem\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\alcar\revature\schoolsystem\schoolsystem\lib\site-packages\flask\app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "c:\users\alcar\revature\schoolsystem\schoolsystem\lib\site-packages\flask\app.py", line 1968, in finalize_request
    response = self.make_response(rv)
  File "c:\users\alcar\revature\schoolsystem\schoolsystem\lib\site-packages\flask\app.py", line 2097, in make_response
    raise TypeError(
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2020-07-07 20:44:05,452 - werkzeug:113 - INFO - 127.0.0.1 - - [07/Jul/2020 20:44:05] "[35m[1mDELETE /users HTTP/1.1[0m" 500 -
2020-07-07 20:45:11,680 - werkzeug:113 - INFO -  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2020-07-07 20:45:14,496 - werkzeug:113 - INFO - 127.0.0.1 - - [07/Jul/2020 20:45:14] "[37mOPTIONS /users HTTP/1.1[0m" 200 -
2020-07-07 20:45:14,747 - werkzeug:113 - INFO - 127.0.0.1 - - [07/Jul/2020 20:45:14] "[37mDELETE /users HTTP/1.1[0m" 204 -
2020-07-07 20:45:17,071 - werkzeug:113 - INFO - 127.0.0.1 - - [07/Jul/2020 20:45:17] "[37mOPTIONS /users HTTP/1.1[0m" 200 -
2020-07-07 20:45:17,378 - SchoolSystem.data.mongo:23 - INFO - Attempting to retrieve user from database
2020-07-07 20:45:17,882 - werkzeug:113 - INFO - 127.0.0.1 - - [07/Jul/2020 20:45:17] "[37mPOST /users HTTP/1.1[0m" 200 -
2020-07-07 20:45:19,086 - werkzeug:113 - INFO - 127.0.0.1 - - [07/Jul/2020 20:45:19] "[37mDELETE /users HTTP/1.1[0m" 204 -
